package entity

enum class TurnOptions {
    NATURE_TOKEN_FREE_SELECTION,
    NATURE_TOKEN_CHANGE_WILDLIFE,
    CLEAR_SEMIPOPULATION,
    MAKE_SELECTION,
    PLACE_HABITAT_TILE,
    PLACE_WILDLIFE_TOKEN,
    DISCARD_WILDLIFE_TOKEN,
}